---
swagger: "2.0"
info:
  description: This is a simple API
  version: 1.0.1
  title: Simple Inventory API
  contact:
    email: aravind.a.padmanabhan@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: virtserver.swaggerhub.com
basePath: /aparavind/netraLib/1.0.1
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
schemes:
- https
paths:
  /inventory:
    get:
      tags:
      - developers
      summary: searches inventory
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      operationId: searchInventory
      produces:
      - application/json
      parameters:
      - name: searchString
        in: query
        description: pass an optional search string for looking up inventory
        required: false
        type: string
      - name: skip
        in: query
        description: number of records to skip for pagination
        required: false
        type: integer
        minimum: 0
        format: int32
      - name: limit
        in: query
        description: maximum number of records to return
        required: false
        type: integer
        maximum: 50
        minimum: 0
        format: int32
      responses:
        "200":
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/InventoryItem'
        "400":
          description: bad input parameter
    post:
      tags:
      - admins
      summary: adds an inventory item
      description: Adds an item to the system
      operationId: addInventory
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: inventoryItem
        description: Inventory item to add
        required: false
        schema:
          $ref: '#/definitions/InventoryItem'
      responses:
        "201":
          description: item created
        "400":
          description: invalid input, object invalid
        "409":
          description: an existing item already exists
definitions:
  InventoryItem:
    type: object
    required:
    - id
    - name
    properties:
      id:
        type: string
        format: pattern
        example: ABC200012
        description: This is the id of the book.the barcode will hopefully be already stuck
        pattern: ^[A-Z]{3}[0-9]{6}$
      name:
        type: string
        example: Rigveda
        description: This is the name of the book
      contentType:
        type: string
        description: Can be on of the options
        enum:
        - Religious
        - School_book
        - Comic
        - Newspaper
      bookType:
        type: string
        description: This describes the book
        enum:
        - Notebook
        - TextBook
        - DrawingBook
        - Files
      owner:
        type: string
        enum:
        - srinidhi
        - aravind
        - vasu
