/**
* Simple Inventory API
* This is a simple API
*
* OpenAPI spec version: 1.0.1
* Contact: aravind.a.padmanabhan@gmail.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param id This is the id of the book.the barcode will hopefully be already stuck
 * @param name This is the name of the book
 * @param contentType Can be on of the options
 * @param bookType This describes the book
 * @param owner 
 */
data class InventoryItem (
    /* This is the id of the book.the barcode will hopefully be already stuck */
    val id: kotlin.String,
    /* This is the name of the book */
    val name: kotlin.String,
    /* Can be on of the options */
    val contentType: InventoryItem.ContentType? = null,
    /* This describes the book */
    val bookType: InventoryItem.BookType? = null,
    val owner: InventoryItem.Owner? = null
) {

    /**
    * Can be on of the options
    * Values: religious,schoolBook,comic,newspaper
    */
    enum class ContentType(val value: kotlin.String){
    
        @Json(name = "Religious") religious("Religious"),
    
        @Json(name = "School_book") schoolBook("School_book"),
    
        @Json(name = "Comic") comic("Comic"),
    
        @Json(name = "Newspaper") newspaper("Newspaper");
    
    }

    /**
    * This describes the book
    * Values: notebook,textBook,drawingBook,files
    */
    enum class BookType(val value: kotlin.String){
    
        @Json(name = "Notebook") notebook("Notebook"),
    
        @Json(name = "TextBook") textBook("TextBook"),
    
        @Json(name = "DrawingBook") drawingBook("DrawingBook"),
    
        @Json(name = "Files") files("Files");
    
    }

    /**
    * 
    * Values: srinidhi,aravind,vasu
    */
    enum class Owner(val value: kotlin.String){
    
        @Json(name = "srinidhi") srinidhi("srinidhi"),
    
        @Json(name = "aravind") aravind("aravind"),
    
        @Json(name = "vasu") vasu("vasu");
    
    }

}

