/**
* Simple Inventory API
* This is a simple API
*
* OpenAPI spec version: 1.0.1
* Contact: aravind.a.padmanabhan@gmail.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.apis

import io.swagger.client.models.InventoryItem

import io.swagger.client.infrastructure.*

class AdminsApi(basePath: kotlin.String = "https://virtserver.swaggerhub.com/aparavind/netraLib/1.0.1") : ApiClient(basePath) {

    /**
    * adds an inventory item
    * Adds an item to the system
    * @param inventoryItem Inventory item to add (optional)
    * @return void
    */
    fun addInventory(inventoryItem: InventoryItem) : Unit {
        val localVariableBody: kotlin.Any? = inventoryItem
        val localVariableQuery: MultiValueMap = mapOf()
        
        val contentHeaders: kotlin.collections.Map<kotlin.String,kotlin.String> = mapOf()
        val acceptsHeaders: kotlin.collections.Map<kotlin.String,kotlin.String> = mapOf("Accept" to "application/json")
        val localVariableHeaders: kotlin.collections.MutableMap<kotlin.String,kotlin.String> = mutableMapOf()
        localVariableHeaders.putAll(contentHeaders)
        localVariableHeaders.putAll(acceptsHeaders)
        
        val localVariableConfig = RequestConfig(
            RequestMethod.POST,
            "/inventory",
            query = localVariableQuery,
            headers = localVariableHeaders
        )
        val response = request<Unit>(
            localVariableConfig,
            localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
            else -> throw kotlin.IllegalStateException("Undefined ResponseType.")
        }
    }

}
